### PR TITLE
Fix font error when font is used by multiple features

### PR DESCRIPTION
**Pull request by yufeizhu600**
This PR is a workaround fix for issue#10.
The root cause of the issue#10 is that when introducing the new feature which accept a font_path and font_size as args for add_text() broken the backward compatibility of passing an aggdraw Font object to the function.

This PR restore the compatibility to use font_obj as below, which is also presented in the document.
 
```font_obj = aggdraw.Font('white', '/usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif.ttf', size=26)```
```dc.add_text("Some Text", font=font_obj)```

I consider it is just a workaround since there is still confusion in the code base that self.style[font] can be either a aggdraw font object or a path to the font file.

### CODE REVIEW

**Comment by djhoese** [comment]
Sorry about missing this. What is the state of this? Is it still needed?

**Comment by yufeizhu600** [comment]
Yes, I think so. It is better to be merged untill a review of the font argument, or review the documents and examples refered font parameter.

**Comment by djhoese** [comment]
After #12 is merged, we can maybe rebase this, merge it, then close #10.

**Comment by djhoese** [comment]
Thanks again @yufeizhu600. I would ask for tests but we don't even have real tests for this project yet and I'm not going to make this PR implement it.

**Pull request merged**
